image: golang:1.12

cache:
  paths:
    - $CI_PROJECT_DIR/vendor

stages:
  - build

before_script:
  - export GOPATH="$CI_PROJECT_DIR/vendor"

build:
  stage: build
  script:
    - GOARCH="amd64" GOOS="linux" go build -o terraform-provider-awx_linux_amd64
    - GOARCH="amd64" GOOS="windows" go build -o terraform-provider-awx_x86_64
    - GOARCH="amd64" GOOS="darwin" go build -o terraform-provider-awx_darwin_amd64
  artifacts:
    paths:
      - terraform-provider-awx_linux_amd64
      - terraform-provider-awx_windows_x86_64
      - terraform-provider-awx_darwin_amd64